on:
  workflow_dispatch:
  schedule:
    # run every one hour
    - cron: '20 */1 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: Baneeishaque/Scoop-GitHub-Actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
